####################### TIGER ##################
---
apiVersion: v1
kind: Service
metadata:
  name: tiger-svc
spec:  
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: tiger