####################### PDF SVC #######################
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-api-svc
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: pdf-api