######################### PDF ########################
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tiger
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tiger
    spec:
      containers:
      - name: tiger
        image: us.gcr.io/totvs-store/tiger:IMAGE_VERSION
        imagePullPolicy: Always
        
        readinessProbe:
          httpGet:
            port: 3000
            path: /api/stats/health
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 1
          timeoutSeconds: 1
          